name: CI/CD Tienda Perritos AWS ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  # REEMPLAZA EL "381491982193" POR TU ID DE CUENTA DE AWS ACADEMY listoco
  ACCOUNT_ID: "381491982193"
               

jobs:
  # ==========================================
  # CAPA DE BASE DE DATOS (DB)
  # ==========================================
  deploy-db:
    name: Build & Push DB
    runs-on: ubuntu-latest
    # Este condicional hace que el job solo corra si cambias algo en la carpeta 'db' o el workflow
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Autenticarse en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Compilar y publicar imagen DB en ECR
      run: |
        docker build -t ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tienda-db:latest ./db
        docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tienda-db:latest

  # ==========================================
  # CAPA DEL BACKEND (API)
  # ==========================================
  deploy-backend:
    name: Build & Push Backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Autenticarse en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Compilar y publicar imagen Backend en ECR
      run: |
        docker build -t ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tienda-backend:latest ./backend
        docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tienda-backend:latest

  # ==========================================
  # CAPA DEL FRONTEND (WEB)
  # ==========================================
  deploy-frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Autenticarse en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Compilar y publicar imagen Frontend en ECR
      run: |
        docker build -t ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tienda-frontend:latest ./frontend
        docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tienda-frontend:latest
